In [1]:
import pandas as pd

In [2]:
from datasets import load_dataset

In [4]:
#loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [6]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [12]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [21]:
min_salary = df['salary_year_avg'].idxmin()
max_salary = df['salary_year_avg'].idxmax()
df.iloc[max_salary]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Name: 554784, dtype: object

In [22]:
df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [40]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']] \
  .agg(['min', 'max', 'median', 'mean', 'count']) \
  .sort_values(by=('salary_year_avg', 'median'), ascending=False)

                          salary_year_avg                                     \
                                      min       max    median           mean
job_title_short
Senior Data Scientist             45000.0  890000.0  155500.0  154206.292996
Senior Data Engineer              35000.0  425000.0  147500.0  145840.611624
Data Scientist                    27000.0  960000.0  127500.0  135988.837171
Data Engineer                     15000.0  525000.0  125000.0  130125.604250
Senior Data Analyst               30000.0  425000.0  111175.0  113911.363665
Machine Learning Engineer         30000.0  325000.0  106415.0  126774.315972
Software Engineer                 28000.0  375000.0   99150.0  113393.760054
Cloud Engineer                    42000.0  280000.0   90000.0  111268.453846
Data Analyst                      25000.0  650000.0   90000.0   93841.907854
Business Analyst                  16500.0  387460.0   85000.0   91082.612833

                                salary_hour_avg                               \
                          count             min    max     median       mean
job_title_short
Senior Data Scientist      1690          17.500  150.0  47.620003  54.105631
Senior Data Engineer       1591          12.500  170.0  61.500000  62.848496
Data Scientist             5922           8.000  237.5  47.500000  49.361403
Data Engineer              4500           8.000  184.5  58.500000  57.196998
Senior Data Analyst        1131          13.000  130.0  47.500000  47.661218
Machine Learning Engineer   576          10.000   87.5  47.535000  48.477935
Software Engineer           467          11.000  102.5  47.560001  46.452019
Cloud Engineer               65          18.500   91.0  40.000000  45.560715
Data Analyst               5451           8.000  391.0  32.615002  38.106918
Business Analyst            610          10.835  132.5  40.362499  42.723415


                          count
job_title_short
Senior Data Scientist       325
Senior Data Engineer        429
Data Scientist             2581
Data Engineer              2277
Senior Data Analyst         353
Machine Learning Engineer    46
Software Engineer           104
Cloud Engineer               21
Data Analyst               4138
Business Analyst            388